"""Add group_key to explore_banners and backfill existing rows.

Revision ID: 010_add_group_key_to_explore_banners
Revises: 009_explore_banner_drop_slot
Create Date: 2026-07-29 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


revision = '010_add_group_key_to_explore_banners'
down_revision = '009_explore_banner_drop_slot'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('explore_banners', sa.Column('group_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_explore_banners_group_key'), 'explore_banners', ['group_key'], unique=False)

    # Backfill data for the 3 existing rows based on their titles.
    # Using raw SQL for directness.
    op.execute("""
        UPDATE explore_banners
        SET group_key = 'hero'
        WHERE title = 'Latest collection'
    """)
    op.execute("""
        UPDATE explore_banners
        SET group_key = 'category'
        WHERE title = 'Explore different categories'
    """)
    op.execute("""
        UPDATE explore_banners
        SET group_key = 'spotlight'
        WHERE title = 'Spotlight banner'
    """)

    # Now that all rows are populated, make the column non-nullable.
    op.alter_column('explore_banners', 'group_key',
               existing_type=sa.String(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explore_banners_group_key'), table_name='explore_banners')
    op.drop_column('explore_banners', 'group_key')
    # ### end Alembic commands ###
